Lock guava version to the version used in Jenkins 1.580.3
To avoid runtime NoSuchMethodError
If newer guava is needed then would need to use the pluginFirstClassLoader

Fix compilation error in older guava